import type { Config } from "tailwindcss";

const inter = ["var(--font-inter)", "Inter", "sans-serif"];

// Tokens copied from the "Luminescent Glass Studio" design system (Stitch).
const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        background: "#f8faf7",
        "tertiary-container": "#5f6d5c",
        "on-secondary-container": "#536651",
        "inverse-on-surface": "#eff1ee",
        "on-primary-fixed-variant": "#394b37",
        surface: "#f8faf7",
        tertiary: "#475545",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        primary: "#425641",
        "on-error": "#ffffff",
        outline: "#747871",
        "on-secondary-fixed-variant": "#394b39",
        "on-primary-container": "#d9f0d4",
        "primary-fixed": "#d2e9cd",
        "primary-fixed-dim": "#b7cdb2",
        "surface-tint": "#50634e",
        "secondary-fixed": "#d3e8cf",
        "inverse-surface": "#2e312f",
        "on-surface-variant": "#434842",
        "on-primary-fixed": "#0e1f0f",
        "on-secondary-fixed": "#0f1f10",
        "surface-container-highest": "#e1e3e0",
        "surface-container": "#eceeeb",
        "on-tertiary-fixed": "#121e12",
        "tertiary-fixed": "#d8e7d3",
        "inverse-primary": "#b7cdb2",
        "tertiary-fixed-dim": "#bccbb7",
        "error-container": "#ffdad6",
        "outline-variant": "#c3c8bf",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f4f1",
        secondary: "#51634f",
        "secondary-fixed-dim": "#b8ccb4",
        "on-tertiary-container": "#dfeed9",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#cee3c9",
        "on-surface": "#191c1b",
        "surface-dim": "#d8dbd8",
        "surface-bright": "#f8faf7",
        "on-background": "#191c1b",
        "on-tertiary-fixed-variant": "#3d4a3b",
        "primary-container": "#5a6e58",
        "surface-container-high": "#e7e9e6",
        "surface-variant": "#e1e3e0",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "gutter-mobile": "1rem",
        "space-lg": "2rem",
        "space-sm": "0.75rem",
        "space-xs": "0.375rem",
        "space-md": "1.25rem",
        margin: "3rem",
        "space-xl": "3.5rem",
        "margin-mobile": "1.25rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        "headline-lg-mobile": inter,
        "label-sm": inter,
        "body-lg": inter,
        "display-hero": inter,
        "headline-md": inter,
        "label-md": inter,
        "headline-lg": inter,
        "title-md": inter,
        "display-hero-mobile": inter,
        "body-md": inter,
      },
      keyframes: {
        "card-in": {
          from: { opacity: "0", transform: "translateY(12px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "card-in": "card-in 300ms ease-out",
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "display-hero": ["64px", { lineHeight: "72px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
